Refactor dnsmasq options
Now all the options configured in dnsmasq are explicitly given as parameters
at launch time. There are no config files involved now.

Also, more useful log info is displayed.

diff --git a/startvm b/startvm
--- a/startvm
+++ b/startvm
@@ -172,11 +172,14 @@ configureNetworks () {
     mknod "/dev/$vtapdev" c $major $minor
 
     # dnsmasq configuration:
-    cat << EOF > "$DNSMASQ_CONF_DIR"/"$iface".conf
-dhcp-range=$IP,$IP
-dhcp-host=$MAC,,$IP,infinite
-dhcp-option=option:netmask,$(cidr2mask $CIDR)
-EOF
+    if [[ "$ENABLE_DHCP" == 1 ]]; then
+      echo "INFO: DHCP configured to serve IP $IP/$CIDR via $vtapdev"
+      DNSMASQ_OPTS="$DNSMASQ_OPTS                       \
+        --dhcp-range=$IP,$IP                            \
+        --dhcp-host=$MAC,,$IP,infinite                  \
+        --dhcp-option=option:netmask,$(cidr2mask $CIDR) \
+        "
+    fi
 
     # kvm configuration:
     let fd=$i+3
@@ -208,6 +211,12 @@ case "$AUTO_ATTACH" in
   *      ) echo "ERROR: AUTO_ATTACH incorrect or not defined. It must be one of YyNn"; exit 1;;
 esac
 
+case "$ENABLE_DHCP" in
+  [Yy1]* ) ENABLE_DHCP=1;;
+  [Nn0]* ) ENABLE_DHCP=0;;
+  *      ) echo "ERROR: ENABLE_DHCP incorrect or not defined. It must be one of [YyNn]"; exit 1;;
+esac
+
 if [[ $AUTO_ATTACH -eq 1 ]]; then
   # Get all interfaces:
   local_ifaces=($(ip link show | grep -v noop | grep state | grep -v LOOPBACK | awk '{print $2}' | tr -d : | sed 's/@.*$//'))
@@ -225,20 +234,18 @@ DEFAULT_ROUTE=$(ip route | grep default | awk '{print $3}')
 
 configureNetworks
 
-case "$ENABLE_DHCP" in
-  [Yy1]* )  DNSMASQ_OPTS="$DNSMASQ_OPTS                       \
-            --dhcp-option=option:dns-server,$DNS_SERVERS      \
-            --dhcp-option=option:router,$DEFAULT_ROUTE        \
-            "
-            [[ -z $(hostname -d) ]] || DNSMASQ_OPTS="$DNSMASQ_OPTS --dhcp-option=option:domain-name,$(hostname -d)"
-            echo "Lauching dnsmasq $DNSMASQ_OPTS"
-            $DNSMASQ $DNSMASQ_OPTS;;
-  [Nn0]* ) ;;
-  *      ) echo "ERROR: ENABLE_DHCP incorrect or not defined. It must be one of [YyNn]"; exit 1;;
-esac
+if [[ "$ENABLE_DHCP" == 1 ]]; then
+  DNSMASQ_OPTS="$DNSMASQ_OPTS                     \
+    --dhcp-option=option:dns-server,$DNS_SERVERS  \
+    --dhcp-option=option:router,$DEFAULT_ROUTE    \
+    "
+  [[ -z $(hostname -d) ]] || DNSMASQ_OPTS="$DNSMASQ_OPTS --dhcp-option=option:domain-name,$(hostname -d)"
+  echo "INFO: Lauching dnsmasq $DNSMASQ_OPTS"
+  $DNSMASQ $DNSMASQ_OPTS
+fi
 
 # KVM_ARGS="$@"
 
 
-echo "Launching $LAUNCHER -enable-kvm $KVM_BLK_OPTS $KVM_OPTS $KVM_CPU_OPTS $KVM_ARGS $@ $KVM_NET_OPTS"
+echo "INFO: Launching $LAUNCHER -enable-kvm $KVM_BLK_OPTS $KVM_OPTS $KVM_CPU_OPTS $KVM_ARGS $@ $KVM_NET_OPTS"
 eval exec $LAUNCHER -enable-kvm $KVM_BLK_OPTS $KVM_OPTS $KVM_CPU_OPTS "$@" $KVM_NET_OPTS
