Manage multiple IPs per NIC in container.
See README for further info on this feature

diff --git a/startvm b/startvm
--- a/startvm
+++ b/startvm
@@ -113,9 +113,39 @@ configureNetworks () {
 
   local GATEWAY=$(ip r | grep default | awk '{print $3}')
 
-  for iface in "${local_ifaces[@]}"
-  do
-    local IP=$(ip address show dev $iface | grep -m1 inet | awk '/inet / { print $2 }' | cut -f1 -d/)
+  for iface in "${local_ifaces[@]}"; do
+
+    # If the container has more than one IP configured in a given interface,
+    # the user can select which one to use.
+    # The SELECTED_NETWORK environment variable is used to select that IP.
+    # This env variable must be in the form IP/MASK (e.g. 1.2.3.4/24).
+    #
+    # If this env variable is not set, the IP to be given to the VM is
+    # the first in the list for that interface (default behaviour).
+
+    local IPs=$(ip address show dev $iface | grep inet | awk '/inet / { print $2 }' | cut -f1 -d/)
+    IPs=($IPs)
+
+    if ! [[ -z "$SELECTED_NETWORK" ]]; then
+      local given_ip given_mask
+      IFS=/ read given_ip given_mask <<< $SELECTED_NETWORK
+      local given_addr=$(atoi $given_ip)
+      local given_mask=$((0xffffffff << (32 - $given_mask) & 0xffffffff))
+      local given_broadcast=$((given_addr | ~given_mask & 0xffffffff))
+      local given_network=$((given_addr & given_mask))
+
+      for configured_ip in "${IPs[@]}"; do
+        local configured_ip=$(atoi $configured_ip)
+        if [[ $configured_ip -gt $given_network && $configured_ip -lt $given_broadcast ]]; then
+          IP=$configured_ip
+          echo "INFO: SELECTED_NETWORK ($SELECTED_NETWORK) found with ip $(itoa $IP) in $iface interface."
+        fi
+      done
+      [[ -z "$IP" ]] && echo "WARNING: SELECTED_NETWORK ($SELECTED_NETWORK) not found in $iface interface."
+    else
+      IP=${IP[0]}
+    fi
+
     local CIDR=$(ip address show dev $iface | awk "/inet $IP/ { print \$2 }" | cut -f2 -d/)
     local vtapdev="macvtap$i"
     local vlandev="macvlan$i"
