KVM container now creates bridges and attaches DH
See improved README.md for changes

diff --git a/startvm b/startvm
--- a/startvm
+++ b/startvm
@@ -1,8 +1,9 @@
 #!/bin/bash
 
-QEMU_CONF_DIR='/etc/qemu-kvm/'
+: ${LAUNCHER:='/usr/libexec/qemu-kvm'}
+: ${QEMU_CONF_DIR:='/etc/qemu-kvm/'}
 
-set -x
+# set -x
 
 containsElement () {
   local e
@@ -10,10 +11,72 @@ containsElement () {
   return 1
 }
 
+# configureBridge BRI_NAME [ IF_TO_CONNECT ]
+# if IF_TO_CONNECT is defined, it is added to the bridge device and
+# the bridge gets its IP/MASK config
+setBridge () {
+  local bridge="$1"
+  local iface="$2"
+
+  brctl addbr "$bridge"
+
+  if [[ $# -eq 2 ]]; then
+    local IP=$(ip addr show dev $iface | grep "inet $IP" | awk '{print $2}' | cut -f1 -d/)
+    local CIDR=$(ip addr show dev $iface | grep "inet $IP" | awk '{print $2}' | cut -f2 -d/)
+
+    brctl addif "$bridge" "$iface"
+    ip address del "$IP/$CIDR" dev "$iface"
+    ip address add "$IP/$CIDR" dev "$bridge"
+  fi
+
+  ip link set dev "$bridge" up
+
+}
+
+# Bring up bridge interfaces and configure KVM options for each of them.
+configureNetwork () {
+  local i=0
+
+  for iface in "${local_ifaces[@]}"; do
+    bri_iface="kvmbri$i"
+
+    setBridge "$bri_iface" "$iface"
+
+    echo 'allow '$iface >> $QEMU_CONF_DIR/bridge.conf
+    KVM_NET_OPTS="$KVM_NET_OPTS -netdev bridge,br=$bri_iface,id=net$i -device virtio-net-pci,netdev=net$i"
+
+    let i++
+  done
+}
+
 # For debugging
 if [ "$1" = "bash" ]; then
   exec bash
 fi
+
+case $AUTO_ATTACH in
+    [Yy]* ) AUTO_ATTACH=1;;
+    [Nn]* ) AUTO_ATTACH=0;;
+    * ) echo "ERROR: AUTO_ATTACH variable not defined."; exit 1;;
+esac
+
+if [[ $AUTO_ATTACH -eq 1 ]]; then
+  # Get all interfaces:
+  local_ifaces=($(ip link show | grep state | grep -v LOOPBACK | awk '{print $2}' | tr -d : | sed 's/@.*$//'))
+  local_bridges=($(brctl show | tail -n +2 | awk '{print $1}'))
+  echo "${local_ifaces[@]}"
+  # Get non-bridge interfaces:
+  for i in "${local_bridges[@]}"; do
+    local_ifaces=(${local_ifaces[@]//*$i*})
+    echo "${local_ifaces[@]}"
+  done
+else
+  local_ifaces="$ATTACH_IFS"
+fi
+
+echo "IFS--""${local_ifaces[@]}"
+
+configureNetwork
 
 : ${KVM_BLK_OPTS:="\
   -drive file=/image/image.qcow2,if=none,id=drive-ide0-0-0,format=qcow2,cache=writethrough \
@@ -38,30 +101,8 @@ fi
 
 : ${KVM_ARGS:="-m 1024 -smp 4,sockets=4,cores=1,threads=1"}
 
-bridge_ifaces=$(brctl show | tail -n +2 | sed '/^[\s\t]/d' | awk '{print $1}')
-set -- $bridge_ifaces
 
-# If BRIFACES is defined, attach them to the VM as tap devices
-#
-if ! [ -z "${BRIFACES}" ]; then
-  i=0
-  for iface in $BRIFACES; do
-    if ! [ -z "${bridge_ifaces}" ]; then
-      if ! $(containsElement $iface $bridge_ifaces); then
-        brctl addbr $iface
-        [[ $i -eq 0 ]] && brctl addif $iface eth0
-        ip link set dev $iface up
-      fi
-    else
-      brctl addbr $iface
-      [[ $i -eq 0 ]] && brctl addif $iface eth0
-    fi
-
-    echo 'allow '$iface >> $QEMU_CONF_DIR/bridge.conf
-    KVM_NET_OPTS="$KVM_NET_OPTS -netdev bridge,br=$iface,id=net$i -device virtio-net-pci,netdev=net$i"
-
-    let i++
-  done
-fi
+# CHECK AUTO_ATTACH var
+# If AUTO_ATTACH=no check ATTACH_IFS
 
 exec $LAUNCHER -enable-kvm $KVM_BLK_OPTS $KVM_OPTS $KVM_ARGS $KVM_NET_OPTS
